server:
  port: 8080
  servlet:
    context-path: /nyscms

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB #如果不限制大小，则设置为-1即可
  #数据源
  datasource:
    name: springboot
    url: jdbc:mysql://123.59.199.170:3306/nongyeshe?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: iLoveRetech0705
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 15
  #视图解析层
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  activemq:
    broker-url: tcp://localhost:61616

# 分布式文件系统FDFS配置
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
  - 47.96.165.218:22122
  # 存储服务器storage_server访问地址
  web-server-url: http://47.96.165.218/

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml,classpath:mapper/custom/*Mapper.xml
  type-aliases-package: com.retech.nyscms.entity


logging:
  config: classpath:logback-spring.xml

